twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ga_code: GAcode-123
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
        
when@test:
    twig:
        strict_variables: true
